<?php

namespace DoctrineProxies\__CG__\Modules\Core\App\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Modules\Core\App\Entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'profile', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'enabled', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'isDelete', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'domainOwner', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'userGroup', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'username', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'password', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'email', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'name', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'mobile', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'remember_token', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'appPassword', 'avatar', 'userRole', 'domain', 'loginCount', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'emailVerifiedAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'deletedAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', 'id', 'profile', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'enabled', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'isDelete', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'domainOwner', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'userGroup', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'username', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'password', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'email', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'name', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'mobile', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'remember_token', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'appPassword', 'avatar', 'userRole', 'domain', 'loginCount', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'emailVerifiedAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'deletedAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\User' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function isDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDelete', []);

        return parent::isDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDelete($isDelete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDelete', [$isDelete]);

        return parent::setIsDelete($isDelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomainOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomainOwner', []);

        return parent::getDomainOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomainOwner($domainOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomainOwner', [$domainOwner]);

        return parent::setDomainOwner($domainOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroup', []);

        return parent::getUserGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserGroup($userGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserGroup', [$userGroup]);

        return parent::setUserGroup($userGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', []);

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', [$mobile]);

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberToken', []);

        return parent::getRememberToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRememberToken($remember_token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRememberToken', [$remember_token]);

        return parent::setRememberToken($remember_token);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppPassword', []);

        return parent::getAppPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppPassword($appPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppPassword', [$appPassword]);

        return parent::setAppPassword($appPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppRoles', []);

        return parent::getAppRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppRoles($appRoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppRoles', [$appRoles]);

        return parent::setAppRoles($appRoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', []);

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', [$avatar]);

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', []);

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroups($groups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroups', [$groups]);

        return parent::setGroups($groups);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', []);

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', [$domain]);

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginCount', []);

        return parent::getLoginCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginCount($loginCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginCount', [$loginCount]);

        return parent::setLoginCount($loginCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailVerifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailVerifiedAt', []);

        return parent::getEmailVerifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailVerifiedAt($emailVerifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailVerifiedAt', [$emailVerifiedAt]);

        return parent::setEmailVerifiedAt($emailVerifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

}
