<?php

namespace DoctrineProxies\__CG__\Modules\Production\App\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Config extends \Modules\Production\App\Entities\Config implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'id', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'domain', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'isWarehouse', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'isAutoApproved', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'issueWithWarehouse', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'issueByProductionBatch', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'isMeasurement', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'updatedAt', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'productionProcedure', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'consumptionMethod'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'id', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'domain', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'isWarehouse', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'isAutoApproved', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'issueWithWarehouse', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'issueByProductionBatch', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'isMeasurement', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'updatedAt', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'productionProcedure', '' . "\0" . 'Modules\\Production\\App\\Entities\\Config' . "\0" . 'consumptionMethod'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Config $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', []);

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', [$domain]);

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductionProcedure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductionProcedure', []);

        return parent::getProductionProcedure();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductionProcedure($productionProcedure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductionProcedure', [$productionProcedure]);

        return parent::setProductionProcedure($productionProcedure);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsumptionMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsumptionMethod', []);

        return parent::getConsumptionMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsumptionMethod($consumptionMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsumptionMethod', [$consumptionMethod]);

        return parent::setConsumptionMethod($consumptionMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function isWarehouse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isWarehouse', []);

        return parent::isWarehouse();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsWarehouse($isWarehouse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsWarehouse', [$isWarehouse]);

        return parent::setIsWarehouse($isWarehouse);
    }

    /**
     * {@inheritDoc}
     */
    public function isMeasurement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isMeasurement', []);

        return parent::isMeasurement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMeasurement($isMeasurement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMeasurement', [$isMeasurement]);

        return parent::setIsMeasurement($isMeasurement);
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoApproved()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAutoApproved', []);

        return parent::isAutoApproved();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsAutoApproved($isAutoApproved)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsAutoApproved', [$isAutoApproved]);

        return parent::setIsAutoApproved($isAutoApproved);
    }

    /**
     * {@inheritDoc}
     */
    public function isIssueWithWarehouse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIssueWithWarehouse', []);

        return parent::isIssueWithWarehouse();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssueWithWarehouse($issueWithWarehouse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssueWithWarehouse', [$issueWithWarehouse]);

        return parent::setIssueWithWarehouse($issueWithWarehouse);
    }

    /**
     * {@inheritDoc}
     */
    public function isIssueByProductionBatch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIssueByProductionBatch', []);

        return parent::isIssueByProductionBatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssueByProductionBatch($issueByProductionBatch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssueByProductionBatch', [$issueByProductionBatch]);

        return parent::setIssueByProductionBatch($issueByProductionBatch);
    }

}
