<?php

namespace DoctrineProxies\__CG__\Modules\Accounting\App\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AccountVoucher extends \Modules\Accounting\App\Entities\AccountVoucher implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'id', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'config', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'voucherType', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'masterVoucher', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'accountHead', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'primaryAccountHead', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'secondaryAccountHead', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'name', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'shortName', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'shortCode', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'mode', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'slug', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'status', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'isDefault', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'isPrivate', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'id', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'config', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'voucherType', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'masterVoucher', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'accountHead', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'primaryAccountHead', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'secondaryAccountHead', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'name', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'shortName', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'shortCode', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'mode', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'slug', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'status', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'isDefault', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'isPrivate', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Accounting\\App\\Entities\\AccountVoucher' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AccountVoucher $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfig', []);

        return parent::getConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfig($config)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfig', [$config]);

        return parent::setConfig($config);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoucherType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoucherType', []);

        return parent::getVoucherType();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoucherType($voucherType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoucherType', [$voucherType]);

        return parent::setVoucherType($voucherType);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortName', []);

        return parent::getShortName();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortName($shortName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortName', [$shortName]);

        return parent::setShortName($shortName);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortCode', []);

        return parent::getShortCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortCode($shortCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortCode', [$shortCode]);

        return parent::setShortCode($shortCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMode', []);

        return parent::getMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMode($mode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', [$mode]);

        return parent::setMode($mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function isStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStatus', []);

        return parent::isStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountHeads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountHeads', []);

        return parent::getAccountHeads();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountHeads($accountHeads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountHeads', [$accountHeads]);

        return parent::setAccountHeads($accountHeads);
    }

    /**
     * {@inheritDoc}
     */
    public function isPrivate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPrivate', []);

        return parent::isPrivate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPrivate($isPrivate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPrivate', [$isPrivate]);

        return parent::setIsPrivate($isPrivate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMasterVoucher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMasterVoucher', []);

        return parent::getMasterVoucher();
    }

    /**
     * {@inheritDoc}
     */
    public function setMasterVoucher($masterVoucher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMasterVoucher', [$masterVoucher]);

        return parent::setMasterVoucher($masterVoucher);
    }

    /**
     * {@inheritDoc}
     */
    public function getLedgerAccountHead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLedgerAccountHead', []);

        return parent::getLedgerAccountHead();
    }

    /**
     * {@inheritDoc}
     */
    public function setLedgerAccountHead($ledgerAccountHead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLedgerAccountHead', [$ledgerAccountHead]);

        return parent::setLedgerAccountHead($ledgerAccountHead);
    }

    /**
     * {@inheritDoc}
     */
    public function isDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDefault', []);

        return parent::isDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDefault($isDefault)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDefault', [$isDefault]);

        return parent::setIsDefault($isDefault);
    }

}
