<?php

namespace DoctrineProxies\__CG__\Modules\Core\App\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Warehouse extends \Modules\Core\App\Entities\Warehouse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'id', 'setting', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'name', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'location', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'contractPerson', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'mobile', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'uniqueId', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'email', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'address', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'status', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'isDelete', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'updatedAt', 'domain', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'isDefault'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'id', 'setting', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'name', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'location', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'contractPerson', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'mobile', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'uniqueId', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'email', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'address', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'status', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'isDelete', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'updatedAt', 'domain', '' . "\0" . 'Modules\\Core\\App\\Entities\\Warehouse' . "\0" . 'isDefault'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Warehouse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getSetting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSetting', []);

        return parent::getSetting();
    }

    /**
     * {@inheritDoc}
     */
    public function setSetting($setting): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSetting', [$setting]);

        parent::setSetting($setting);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(string $location): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractPerson(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractPerson', []);

        return parent::getContractPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractPerson(string $contractPerson): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractPerson', [$contractPerson]);

        parent::setContractPerson($contractPerson);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', []);

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile(string $mobile): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', [$mobile]);

        parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $address): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function isStatus(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStatus', []);

        return parent::isStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function isDelete(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDelete', []);

        return parent::isDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDelete(bool $isDelete): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDelete', [$isDelete]);

        parent::setIsDelete($isDelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', []);

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain($domain): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', [$domain]);

        parent::setDomain($domain);
    }

}
