<?php

namespace DoctrineProxies\__CG__\Modules\Inventory\App\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \Modules\Inventory\App\Entities\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'id', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'config', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'categoryNature', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'parent', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'discount', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'expiry_duration', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'name', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'slug', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'code', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'generateId', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'mode', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'sorting', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'weightAvgPriceDuration', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'hasQuantity', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'status', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'isPrivate', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'id', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'config', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'categoryNature', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'parent', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'discount', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'expiry_duration', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'name', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'slug', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'code', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'generateId', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'mode', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'sorting', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'weightAvgPriceDuration', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'hasQuantity', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'status', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'isPrivate', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'createdAt', '' . "\0" . 'Modules\\Inventory\\App\\Entities\\Category' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfig', []);

        return parent::getConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfig($config)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfig', [$config]);

        return parent::setConfig($config);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent($parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getSorting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSorting', []);

        return parent::getSorting();
    }

    /**
     * {@inheritDoc}
     */
    public function setSorting($sorting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSorting', [$sorting]);

        return parent::setSorting($sorting);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeightAvgPriceDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeightAvgPriceDuration', []);

        return parent::getWeightAvgPriceDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeightAvgPriceDuration($weightAvgPriceDuration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeightAvgPriceDuration', [$weightAvgPriceDuration]);

        return parent::setWeightAvgPriceDuration($weightAvgPriceDuration);
    }

    /**
     * {@inheritDoc}
     */
    public function isHasQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHasQuantity', []);

        return parent::isHasQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasQuantity($hasQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasQuantity', [$hasQuantity]);

        return parent::setHasQuantity($hasQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function isStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStatus', []);

        return parent::isStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', []);

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenerateId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenerateId', []);

        return parent::getGenerateId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenerateId($generateId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenerateId', [$generateId]);

        return parent::setGenerateId($generateId);
    }

}
